const books = [
  {
    _id: '1',
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    pages: 417,
    firstEdition: 1967,
    category: 'Novel',
    price: 15.99,
    countInStock: 5,
    image: '/images/onehundred.jpeg',
    rating: 5.0,
    numReviews: 8,
  },
  {
    _id: '2',
    title: 'The Shadow of the Wind',
    author: 'Carlos Ruiz Zafon',
    pages: 487,
    firstEdition: 2001,
    category: 'Novel',
    price: 14.99,
    countInStock: 4,
    image: '/images/shadow.jpeg',
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: '3',
    title: 'Island Beneath the Sea',
    author: 'Isabel Allende',
    pages: 480,
    firstEdition: 2009,
    category: 'Novel',
    price: 18.99,
    countInStock: 4,
    image: '/images/island.jpeg',
    rating: 3.5,
    numReviews: 6,
  },
  {
    _id: '4',
    title: 'The Kingdom of This World',
    author: 'Alejo Carpentier',
    pages: 160,
    firstEdition: 1949,
    category: 'Novel',
    price: 12.99,
    countInStock: 2,
    image: '/images/kingdom.jpeg',
    rating: 4.8,
    numReviews: 5,
  },
];

export default books;
